// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Last generated at 08/11/2025 21:03:27

using System;

namespace RPGFramework.Audio.Sfx_Sample
{
	public enum Sfx_01Enum
	{
	}

	public static class Sfx_01
	{

		public static string GetByEnum(Sfx_01Enum value)
		{
			return value switch
			{
				_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
			};
		}
	}
}
