// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Last generated at 08/11/2025 21:03:27

using System;

namespace RPGFramework.Audio.Sfx_Sample
{
	public enum Sfx_00Enum
	{
		LOOP_START = 0,
		LOOP_END = 1,
	}

	public static class Sfx_00
	{
		public const string LOOP_START = "LoopStart";
		public const string LOOP_END = "LoopEnd";

		public static string GetByEnum(Sfx_00Enum value)
		{
			return value switch
			{
				Sfx_00Enum.LOOP_START => LOOP_START,
				Sfx_00Enum.LOOP_END => LOOP_END,
				_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
			};
		}
	}
}
